### ISSUE TITLE
Use Allowed / Dissallowed elements from .yml

### ISSUE THREAD

**Issue by jthale** [dnadesign/silverstripe-elemental-list#13]
Would be great if we could limit the elements allowed within a list. Don't see how this is possible right now. I see it working like this:

DNADesign\Elemental\Models\ElementList:
  allowed_elements:
    - NAMESPACE\SomeContentElement

**Comment by robbieaverill** [comment]
Yep, like how ElementalAreasExtension allows you to define `allowed_elements` and `disallowed_elements` for a page, right? Ideally we'd abstract this logic out so it can be applied to both a page and a list element (or anything else that contains children).

**Comment by robbieaverill** [comment]
I think we fixed something recently in elemental related to this. Thanks, will close. Happy to reopen if needed!
