### ISSUE TITLE
Extending ElementList

### ISSUE THREAD

**Issue by thezenmonkey** [dnadesign/silverstripe-elemental-list#14]
I'm extending ElementList block to proved different sectioning elements, however the theme always uses ElementList.ss. Should I just extend BaseElement and copy the list Code?

**Comment by robbieaverill** [comment]
Hi @thezenmonkey - I'm not sure I get the issue. Could you please explain it in a little more detail?

**Comment by thezenmonkey** [comment]
@robbieaverill  I currently have the following:

```
use DNADesign\ElementalList\Model\ElementList;

class SectionElement extends ElementList
{
    private static $db = [
        'FullWidth' => 'Boolean'
    ];

    private static $controller_template = 'NoElementHolder';

    private static $template = 'NoElementHolder';

    private static $icon = 'font-icon-block-layout';

    private static $singular_name = 'Section';

    private static $plural_name = 'Sections';

    private static $description = 'Top Level Sectioning Element for Page';

    private static $table_name = 'SectionElement';

    public function getType()
    {
        return _t(__CLASS__ . '.BlockType', 'Section');
    }
}
```
When it renders in template it uses ElementList.ss instead of SectionElement.ss. I've done a ?flush=1, I'm not sure if it's something with my directory structure in SS4.1 or something else

**Comment by robbieaverill** [comment]
Ah ok, thanks. This sounds like a bug. It should render SectionElement if one exists. Have you double checked that your template is in the correct directory structure to match your class namespace?

**Comment by thezenmonkey** [comment]
OK I got it. The class isn't namespaced, it works when the SectionElement.ss is in the themes/mytheme/templates/
