### ISSUE TITLE
Can't find Template

### ISSUE THREAD

**Issue by asecondwill** [dnadesign/silverstripe-elemental-list#3]
Fresh install of SS4 to try out Elemental.  Admin area works, shows blocks interface, allows adding lists.  

Front end shows other Elemental content but if i add a list i get:

```
Warning: None of the following templates could be found: Array ( [0] => DNADesign\ElementalList\Model\ElementList [1] => DNADesign\ElementalList\Model\ElementList ) in themes "Array ( [0] => simple [1] => $default ) " in /Users/will/Sites/www/northerncobalt/wwwroot/vendor/silverstripe/framework/src/View/SSViewer.php on line 210

Warning: file_get_contents(): Filename cannot be empty in /Users/will/Sites/www/northerncobalt/wwwroot/vendor/silverstripe/framework/src/View/SSViewer.php on line 634
```

**Comment by wilr** [comment]
You've flushed correct? Perhaps the ElementList.ss file needs to be moved into a `Model` subfolder right @robbieaverill ?

**Comment by hdpero** [comment]
@asecondwill I got the same error, but as @wilr suggested I've moved ElementList.ss file to Model subfolder and now it works as expected, so it is now `DNADesign\ElementalList\Model\ElementList.ss`.

**Comment by asecondwill** [comment]
Thanks for the suggestions and fix.
