### ISSUE TITLE
Icon doesn't display

### ISSUE THREAD

**Issue by DrMartinGonzo** [dnadesign/silverstripe-elemental-list#8]
`getIcon()` in `BaseElement.php` expects a css class, but ElementList gives `dnadesign/silverstripe-elemental-list:images/list.svg`.
Is that a not yet implemented feature in Elemental or an oversight ? (not sure about the word :))

**Comment by robbieaverill** [comment]
Yep, true. We switched it a while back from an image and forgot to update this module. `font-icon-list` seems relevant - thoughts?

![image](https://user-images.githubusercontent.com/5170590/36626736-d4458390-199c-11e8-9389-16bbd8c81644.png)

Keen for a pull request?

**Comment by DrMartinGonzo** [comment]
`font-icon-block-file-list`looks to be more in the same style of the other icons with thinner line strokes.
![capture d ecran 2018-02-24 a 16 24 54](https://user-images.githubusercontent.com/11061711/36631871-50f33860-197f-11e8-991a-dd2117e5f972.png)
I'll do the pull request.
